package com.mycompany.interfazbaloncesto;

import javax.swing.ImageIcon;
/**
 *
 * @author walth
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setIconImage(new ImageIcon(getClass().getResource("/images/logoCalBal.png")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PantallaPrincipal = new javax.swing.JPanel();
        PantallaDatos = new javax.swing.JPanel();
        cabeceraDatos = new javax.swing.JLabel();
        panelFormulario = new javax.swing.JPanel();
        txtNombre = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        txtTca = new javax.swing.JLabel();
        inputTca = new javax.swing.JTextField();
        txtT3a = new javax.swing.JLabel();
        inputT3a = new javax.swing.JTextField();
        txtTci = new javax.swing.JLabel();
        inputTci = new javax.swing.JTextField();
        fondoDatos = new javax.swing.JLabel();
        PantallaResultados = new javax.swing.JPanel();
        cabeceraResultados = new javax.swing.JLabel();
        resultadoEFG = new javax.swing.JLabel();
        resultadoFG = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonCalcular = new javax.swing.JButton();
        botonMostrar = new javax.swing.JButton();
        botonGlosario = new javax.swing.JButton();
        iconoExcel = new javax.swing.JLabel();
        botonCalcular1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora de Estadisticas de la NBA");

        PantallaPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        PantallaDatos.setBackground(new java.awt.Color(255, 255, 255));
        PantallaDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cabeceraDatos.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cabeceraDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoDatos.png"))); // NOI18N
        cabeceraDatos.setText("Datos:");
        PantallaDatos.add(cabeceraDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 170, 50));

        panelFormulario.setBackground(new java.awt.Color(0, 93, 53));
        panelFormulario.setLayout(new java.awt.GridBagLayout());

        txtNombre.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtNombre.setText("Nombre:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 15;
        panelFormulario.add(txtNombre, gridBagConstraints);

        inputNombre.setForeground(new java.awt.Color(204, 204, 204));
        inputNombre.setText("texto");
        inputNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputNombreFocusLost(evt);
            }
        });
        inputNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 80;
        panelFormulario.add(inputNombre, gridBagConstraints);

        txtTca.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTca.setText("TCA:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 3, 0);
        panelFormulario.add(txtTca, gridBagConstraints);

        inputTca.setForeground(new java.awt.Color(204, 204, 204));
        inputTca.setText("texto");
        inputTca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputTcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputTcaFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 80;
        panelFormulario.add(inputTca, gridBagConstraints);

        txtT3a.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtT3a.setText("T3A:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 3, 0);
        panelFormulario.add(txtT3a, gridBagConstraints);

        inputT3a.setForeground(new java.awt.Color(204, 204, 204));
        inputT3a.setText("texto");
        inputT3a.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputT3aFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputT3aFocusLost(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 80;
        panelFormulario.add(inputT3a, gridBagConstraints);

        txtTci.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTci.setText("TCI:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 0, 3, 0);
        panelFormulario.add(txtTci, gridBagConstraints);

        inputTci.setForeground(new java.awt.Color(204, 204, 204));
        inputTci.setText("texto");
        inputTci.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                inputTciFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                inputTciFocusLost(evt);
            }
        });
        inputTci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTciActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 80;
        panelFormulario.add(inputTci, gridBagConstraints);

        PantallaDatos.add(panelFormulario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 280, 160));

        fondoDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoRedondeadoDatosPruebaNose.png"))); // NOI18N
        PantallaDatos.add(fondoDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, -1, -1));

        PantallaResultados.setBackground(new java.awt.Color(255, 255, 255));
        PantallaResultados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cabeceraResultados.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        cabeceraResultados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/IconoResultado.png"))); // NOI18N
        cabeceraResultados.setText("Resultados:");
        PantallaResultados.add(cabeceraResultados, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 190, -1));

        resultadoEFG.setBackground(new java.awt.Color(255, 255, 255));
        resultadoEFG.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        resultadoEFG.setForeground(new java.awt.Color(255, 255, 255));
        resultadoEFG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoEFG.setText("-%");
        PantallaResultados.add(resultadoEFG, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 120, 60));

        resultadoFG.setBackground(new java.awt.Color(255, 255, 255));
        resultadoFG.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        resultadoFG.setForeground(new java.awt.Color(255, 255, 255));
        resultadoFG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultadoFG.setText("-%");
        PantallaResultados.add(resultadoFG, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 130, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel10.setText("%eFG:");
        PantallaResultados.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoResultados2.png"))); // NOI18N
        PantallaResultados.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 91, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel9.setText("%FG:");
        PantallaResultados.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondoResultados1.png"))); // NOI18N
        PantallaResultados.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 93, 53));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logtipoNBA.png"))); // NOI18N
        jLabel1.setText("Jugador");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 684, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        botonCalcular.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonCalcular.setText("Calcular");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });

        botonMostrar.setText("Mostrar");
        botonMostrar.setToolTipText("");
        botonMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMostrarActionPerformed(evt);
            }
        });

        botonGlosario.setText("Glosario");

        iconoExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logoExcel.png"))); // NOI18N

        botonCalcular1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonCalcular1.setText("Resetear");
        botonCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcular1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PantallaPrincipalLayout = new javax.swing.GroupLayout(PantallaPrincipal);
        PantallaPrincipal.setLayout(PantallaPrincipalLayout);
        PantallaPrincipalLayout.setHorizontalGroup(
            PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(PantallaPrincipalLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PantallaPrincipalLayout.createSequentialGroup()
                        .addComponent(botonGlosario)
                        .addGap(134, 134, 134)
                        .addComponent(botonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PantallaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PantallaPrincipalLayout.createSequentialGroup()
                        .addComponent(PantallaResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(PantallaPrincipalLayout.createSequentialGroup()
                        .addComponent(botonCalcular1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iconoExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonMostrar)
                        .addGap(39, 39, 39))))
        );
        PantallaPrincipalLayout.setVerticalGroup(
            PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PantallaPrincipalLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PantallaResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PantallaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PantallaPrincipalLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconoExcel)
                            .addComponent(botonMostrar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonGlosario, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(PantallaPrincipalLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(PantallaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonCalcular1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PantallaPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PantallaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void focusGainedInput(javax.swing.JTextField input ){
        String texto = input.getText();
        if (texto.equals("texto")){
            input.setText("");
            input.setForeground(new java.awt.Color(0,0,0));
        }
    }
    
    private void focusLostInput(javax.swing.JTextField input){
        String texto = input.getText();
        if (texto.equals("")){
            input.setText("texto");
            input.setForeground(new java.awt.Color(204,204,204));
        }
    }
    
    private void inputTciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTciActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTciActionPerformed

    private void botonMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonMostrarActionPerformed

    private void inputNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreActionPerformed
        
    }//GEN-LAST:event_inputNombreActionPerformed

    private void inputNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombreFocusGained
        focusGainedInput(inputNombre);
    }//GEN-LAST:event_inputNombreFocusGained

    private void inputNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputNombreFocusLost
        focusLostInput(inputNombre);
    }//GEN-LAST:event_inputNombreFocusLost

    private void inputTcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputTcaFocusGained
        focusGainedInput(inputTca);
    }//GEN-LAST:event_inputTcaFocusGained

    private void inputTcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputTcaFocusLost
        focusLostInput(inputTca);
    }//GEN-LAST:event_inputTcaFocusLost

    private void inputT3aFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputT3aFocusGained
        focusGainedInput(inputT3a);
    }//GEN-LAST:event_inputT3aFocusGained

    private void inputT3aFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputT3aFocusLost
        focusLostInput(inputT3a);
    }//GEN-LAST:event_inputT3aFocusLost

    private void inputTciFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputTciFocusGained
        focusGainedInput(inputTci);
    }//GEN-LAST:event_inputTciFocusGained

    private void inputTciFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_inputTciFocusLost
        focusLostInput(inputTci);
    }//GEN-LAST:event_inputTciFocusLost

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed

    // Obtener valores de los tres JTextFields
    int tca = Integer.parseInt(inputTca.getText());
    int t3a = Integer.parseInt(inputT3a.getText());
    int tci = Integer.parseInt(inputTci.getText());

    // hacer las respectivas operaiones
    double fg = ((double)tca/tci) * 100;
    double efg = ((double)(tca + (0.5 * t3a)) / tci) * 100;
    
    // Mostrar el resultado en un JLabel
    resultadoFG.setText(String.format("%.2f",fg) + "%");
    resultadoEFG.setText(String.format("%.2f",efg) + "%");
      
    }//GEN-LAST:event_botonCalcularActionPerformed

    private void botonCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcular1ActionPerformed
        resultadoEFG.setText("-%");
        resultadoFG.setText("-%");
        inputNombre.setText("texto");
        inputNombre.setForeground(new java.awt.Color(204,204,204));
        inputTca.setText("texto");
        inputTca.setForeground(new java.awt.Color(204,204,204));
        inputT3a.setText("texto");
        inputT3a.setForeground(new java.awt.Color(204,204,204));
        inputTci.setText("texto");
        inputTci.setForeground(new java.awt.Color(204,204,204));
        
    }//GEN-LAST:event_botonCalcular1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PantallaDatos;
    private javax.swing.JPanel PantallaPrincipal;
    private javax.swing.JPanel PantallaResultados;
    private javax.swing.JButton botonCalcular;
    private javax.swing.JButton botonCalcular1;
    private javax.swing.JButton botonGlosario;
    private javax.swing.JButton botonMostrar;
    private javax.swing.JLabel cabeceraDatos;
    private javax.swing.JLabel cabeceraResultados;
    private javax.swing.JLabel fondoDatos;
    private javax.swing.JLabel iconoExcel;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputT3a;
    private javax.swing.JTextField inputTca;
    private javax.swing.JTextField inputTci;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelFormulario;
    private javax.swing.JLabel resultadoEFG;
    private javax.swing.JLabel resultadoFG;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtT3a;
    private javax.swing.JLabel txtTca;
    private javax.swing.JLabel txtTci;
    // End of variables declaration//GEN-END:variables
}
